# Generated by Django 5.0.1 on 2024-01-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата урока')),
                ('start_time', models.TimeField(verbose_name='Начало урока')),
                ('end_time', models.TimeField(verbose_name='Конец урока')),
                ('classroom', models.CharField(max_length=50, verbose_name='Аудитория')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название школы')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес школы')),
                ('established', models.DateField(verbose_name='Дата основания школы')),
                ('type', models.CharField(max_length=100, verbose_name='Тип школы')),
                ('website', models.URLField(verbose_name='Веб сайт школы')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя директора')),
                ('age', models.IntegerField(verbose_name='Возраст директора')),
                ('experience', models.IntegerField(verbose_name='Опыт работы директора')),
                ('qualification', models.CharField(max_length=200, verbose_name='Квалификация директора')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='communication.school', verbose_name='Школа которой руководит')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер аудитории')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя студента')),
                ('age', models.IntegerField(verbose_name='Возраст студента')),
                ('grade', models.IntegerField(verbose_name='Класс в котором учится')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.school')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата урока')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('code', models.CharField(max_length=10, verbose_name='Дод предмета')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_subjects', to='communication.school')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.subject'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя учителя')),
                ('age', models.IntegerField(verbose_name='Возраст учителя')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет который преподает')),
                ('experience', models.IntegerField(verbose_name='Опыт работы')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='communication.school')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_subjects', to='communication.teacher'),
        ),
    ]
